services:

  bot-npc:
    image: golang:1.23.4-alpine
    entrypoint: 
      - /bin/sh
      - -c
      - cd /app && go mod tidy && go run main.go
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM=qwen2.5:0.5b
      #- HTTP_PORT=5051
    ports:
      - 5051:8080
    volumes:
      - ./:/app
    networks:
      - ollama-network

volumes:
  ollama-data:
    external: true
    name: ollama_shared_data

networks:
  ollama-network:
    external: true