services:

  generate-names:
    build: .
    command: go run main.go
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      #- OLLAMA_HOST=http://host.docker.internal:11434
      - LLM=qwen2.5:0.5b
    volumes:
      - ./:/app
    networks:
      - ollama-network
    develop:
      watch:
        - action: rebuild
          path: ./main.go
          #target: /app

#volumes:
#  ollama-data:

# First, we need to create the volume: docker volume create ollama_shared_data
volumes:
  ollama-data:
    external: true
    name: ollama_shared_data

networks:
  ollama-network:
    external: true