services:

  ai-workspace:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/arm64"
        - "linux/amd64"
      args:
        - USER_NAME=${USER}
    volumes:
      - ../..:/workspaces:cached   
    command: sleep infinity

  #ollama-service:
  #  build:
  #    context: .
  #    dockerfile: ollama.Dockerfile
