services:

  ollama-service:
    image: ollama/ollama:0.5.4
    volumes:
      - ../ollama-data:/root/.ollama
    ports:
      - 11434:11434

  generate-names:
    build: .
    command: go run main.go; sleep infinity
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM=qwen2.5:0.5b
    volumes:
      - .:/app
    depends_on:
      ollama-service:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./main.go

