services:

  ollama-service:
    image: ollama/ollama:0.5.4
    volumes:
      - ../ollama-data:/root/.ollama
    ports:
      - 11434:11434

  generate-npc-descriptions:
    build: .
    command: go run main.go; sleep infinity
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      #- LLM=qwen2.5:1.5b
      #- LLM=qwen2.5:3b # 🙂
      - LLM=qwen2.5:0.5b
    volumes:
      - ./:/app
    develop:
      watch:
        - action: rebuild
          path: ./main.go
        - action: rebuild
          path: ./instructions.md
        - action: rebuild
          path: ./steps.md
        - action: rebuild
          path: ./character.json          

