services:
  
  ollama-service:
    image: k33g/chronicles-of-aethelgard:0.0.2
    ports:
      - 11434:11434

  golang-version:
    image: golang:1.23.4-alpine
    command: go version
    #entrypoint: 
    #  - /bin/sh
    #  - -c
    #  - go version

